# Generated by Django 5.2.4 on 2025-08-25 21:19

import accounts.models
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_products_product_winner_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='product_end_date',
            field=models.DateTimeField(default=accounts.models.ten_days_later),
        ),
        migrations.AlterField(
            model_name='products',
            name='product_pub_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
