# Generated by Django 5.2.4 on 2025-09-20 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_products_product_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='product_bidders',
            field=models.CharField(default='', max_length=20000),
        ),
        migrations.AlterField(
            model_name='products',
            name='product_winner',
            field=models.CharField(default=-1, max_length=50),
        ),
    ]
